### ISSUE TITLE
info 好像不起错用了，原来airoot-jus是好使的

### ISSUE THREAD

**Issue by ppyang010** [uucckk/AIroot-UISYS#4]
info 好像不起错用了，原来airoot-jus是好使的

**Comment by uucckk** [comment]
您好，这个等我确认下，我再答复给你。

**Comment by uucckk** [comment]
您好 确实存在不输出的问题。
1.如果是找不到文件，是因为，现在.jus 改为 .uisys了
2.如果有这个文件，不输出，是因为程序的bug。
  我现在正在排查

**Comment by uucckk** [comment]
已在 UISYS-RELEASE-0.9.5(RC1) 修正
